<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "account_show_styles".
 *
 * @property int $id
 * @property string $bg_color 背景颜色
 * @property string $text_color 文字颜色
 * @property string $login_group 账号分组
 * @property string $group_icon 图片链接
 * @property int $created_at
 * @property int $updated_at
 */
class AccountShowStyles extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'account_show_styles';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'integer'],
            [['bg_color'], 'string', 'max' => 64],
            [['text_color', 'login_group'], 'string', 'max' => 32],
            [['group_icon'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'bg_color' => 'Bg Color',
            'text_color' => 'Text Color',
            'login_group' => 'Login Group',
            'group_icon' => 'Group Icon',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function beforeSave($insert)
	{
		if ($this->isNewRecord) {
			$this->created_at = time();
		}
		$this->updated_at = time();
		return parent::beforeSave($insert); // TODO: Change the autogenerated stub
	}


}

