<?php
return '{
    "AD": {"name":"Andorra","callingcode":"376", "currency":"EUR", "lang":"ca"},
    "AE": {"name":"United Arab Emirates","callingcode":"971", "currency":"AED", "lang":"ar"},
    "AF": {"name":"Afghanistan","callingcode":"93", "currency":"USD", "lang":"fa"},
    "AG": {"name":"Antigua and Barbuda","callingcode":"1-268", "currency":"XCD", "lang":"en"},
    "AI": {"name":"Anguilla","callingcode":"1-264", "currency":"XCD", "lang":"en"},
    "AL": {"name":"Albania","callingcode":"355", "currency":"EUR", "lang":"sq"},
    "AM": {"name":"Armenia","callingcode":"374", "currency":"AMD", "lang":"hy"},
    "AO": {"name":"Angola","callingcode":"244", "currency":"AOA", "lang":"pt"},
    "AR": {"name":"Argentina","callingcode":"54", "currency":"ARS", "lang":"es"},
    "AS": {"name":"American Samoa","callingcode":"1-684", "currency":"USD", "lang":"sm"},
    "AT": {"name":"Austria","callingcode":"43", "currency":"EUR", "lang":"de"},
    "AU": {"name":"Australia","callingcode":"61", "currency":"AUD", "lang":"en"},
    "AW": {"name":"Aruba","callingcode":"297", "currency":"AWG", "lang":"en"},
    "AX": {"name":"\u00c5land Islands","callingcode":"358", "currency":"EUR", "lang":"en"},
    "AZ": {"name":"Azerbaijan","callingcode":"994", "currency":"AZM", "lang":"az"},
    "BA": {"name":"Bosnia and Herzegovina","callingcode":"387", "currency":"BAM", "lang":"bs"},
    "BB": {"name":"Barbados","callingcode":"1-246", "currency":"BBD", "lang":"en"},
    "BD": {"name":"Bangladesh","callingcode":"880", "currency":"BDT", "lang":"bn"},
    "BE": {"name":"Belgium","callingcode":"32", "currency":"EUR", "lang":"nl"},
    "BF": {"name":"Burkina Faso","callingcode":"226", "currency":"XOF", "lang":"fr"},
    "BG": {"name":"Bulgaria","callingcode":"359", "currency":"EUR", "lang":"bg"},
    "BH": {"name":"Bahrain","callingcode":"973", "currency":"BHD", "lang":"ar"},
    "BI": {"name":"Burundi","callingcode":"257", "currency":"BIF", "lang":"fr"},
    "BJ": {"name":"Benin","callingcode":"229", "currency":"XOF", "lang":"fr"},
    "BM": {"name":"Bermuda","callingcode":"1-441", "currency":"BMD", "lang":"en"},
    "BN": {"name":"Brunei Darussalam","callingcode":"BN", "currency":"BND", "lang":"en"},
    "BO": {"name":"Bolivia, Plurinational State of","callingcode":"591", "currency":"BOB", "lang":"en"},
    "BR": {"name":"Brazil","callingcode":"55", "currency":"BRL", "lang":"pt"},
    "BS": {"name":"Bahamas","callingcode":"1-242", "currency":"BSD", "lang":"en"},
    "BT": {"name":"Bhutan","callingcode":"975", "currency":"BTN", "lang":"dz"},
    "BW": {"name":"Botswana","callingcode":"267", "currency":"BWP", "lang":"tn"},
    "BY": {"name":"Belarus","callingcode":"375", "currency":"BYR", "lang":"ru"},
    "BZ": {"name":"Belize","callingcode":"501", "currency":"BZD", "lang":"en"},
    "CA": {"name":"Canada","callingcode":"1", "currency":"CAD", "lang":"en"},
    "CC": {"name":"Cocos (Keeling) Islands","callingcode":"61", "currency":"USD", "lang":"en"},
    "CD": {"name":"Congo, the Democratic Republic of the","callingcode":"243", "currency":"CDF", "lang":"fr"},
    "CF": {"name":"Central African Republic","callingcode":"236", "currency":"XAF", "lang":"fr"},
    "CG": {"name":"Congo","callingcode":"242", "currency":"XAF", "lang":"fr"},
    "CH": {"name":"Switzerland","callingcode":"41", "currency":"CHF", "lang":"de"},
    "CI": {"name":"C\u00f4te d\'Ivoire","callingcode":"225", "currency":"XOF", "lang":"fr"},
    "CK": {"name":"Cook Islands","callingcode":"682", "currency":"NZD", "lang":"en"},
    "CL": {"name":"Chile","callingcode":"56", "currency":"CLP", "lang":"es"},
    "CM": {"name":"Cameroon","callingcode":"237", "currency":"XAF", "lang":"fr"},
    "CN": {"name":"China","callingcode":"86", "currency":"CNY", "lang":"zh-CN","currency_symbol":"¥"},
    "CO": {"name":"Colombia","callingcode":"57", "currency":"COP", "lang":"es"},
    "CR": {"name":"Costa Rica","callingcode":"506", "currency":"CRC", "lang":"es"},
    "CU": {"name":"Cuba","callingcode":"53", "currency":"USD", "lang":"es"},
    "CV": {"name":"Cape Verde","callingcode":"238", "currency":"CVE", "lang":"pt"},
    "CW": {"name":"Cura\u00e7ao","callingcode":"599", "currency":"USD", "lang":"en"},
    "CX": {"name":"Christmas Island","callingcode":"61", "currency":"USD", "lang":"en"},
    "CY": {"name":"Cyprus","callingcode":"357", "currency":"EUR", "lang":"en"},
    "CZ": {"name":"Czech Republic","callingcode":"420", "currency":"CZK", "lang":"cs"},
    "DE": {"name":"Germany","callingcode":"49", "currency":"EUR", "lang":"de"},
    "DJ": {"name":"Djibouti","callingcode":"253", "currency":"DJF", "lang":"fr"},
    "DK": {"name":"Denmark","callingcode":"45", "currency":"DKK", "lang":"da"},
    "DM": {"name":"Dominica","callingcode":"1-767", "currency":"XCD", "lang":"en"},
    "DO": {"name":"Dominican Republic","callingcode":"1-809", "currency":"DOP", "lang":"es"},
    "DZ": {"name":"Algeria","callingcode":"213", "currency":"DZD", "lang":"ar"},
    "EC": {"name":"Ecuador","callingcode":"593", "currency":"USD", "lang":"es"},
    "EE": {"name":"Estonia","callingcode":"372", "currency":"EEK", "lang":"et"},
    "EG": {"name":"Egypt","callingcode":"20", "currency":"EGP", "lang":"ar"},
    "ER": {"name":"Eritrea","callingcode":"291", "currency":"ERN", "lang":"aa"},
    "ES": {"name":"Spain","callingcode":"34", "currency":"EUR", "lang":"es"},
    "ET": {"name":"Ethiopia","callingcode":"251", "currency":"ETB", "lang":"am"},
    "FI": {"name":"Finland","callingcode":"358", "currency":"EUR", "lang":"fi"},
    "FJ": {"name":"Fiji","callingcode":"679", "currency":"FJD", "lang":"en"},
    "FK": {"name":"Falkland Islands (Malvinas)","callingcode":"500", "currency":"USD", "lang":"en"},
    "FM": {"name":"Micronesia, Federated States of","callingcode":"691", "currency":"USD", "lang":"en"},
    "FO": {"name":"Faroe Islands","callingcode":"298", "currency":"DKK", "lang":"en"},
    "FR": {"name":"France","callingcode":"33", "currency":"EUR", "lang":"fr"},
    "GA": {"name":"Gabon","callingcode":"241", "currency":"XAF", "lang":"fr"},
    "GB": {"name":"United Kingdom","callingcode":"44", "currency":"GBP", "lang":"en"},
    "GD": {"name":"Grenada","callingcode":"1-473", "currency":"XCD", "lang":"en"},
    "GE": {"name":"Georgia","callingcode":"995", "currency":"GEL", "lang":"ka"},
    "GG": {"name":"Guernsey","callingcode":"44-1481", "currency":"GBP", "lang":"en"},
    "GH": {"name":"Ghana","callingcode":"233", "currency":"GHC", "lang":"en"},
    "GI": {"name":"Gibraltar","callingcode":"350", "currency":"GIP", "lang":"en"},
    "GL": {"name":"Greenland","callingcode":"299", "currency":"DKK", "lang":"en"},
    "GM": {"name":"Gambia","callingcode":"220", "currency":"GMD", "lang":"en"},
    "GN": {"name":"Guinea","callingcode":"224", "currency":"GNF", "lang":"fr"},
    "GQ": {"name":"Equatorial Guinea","callingcode":"240", "currency":"XAF", "lang":"es"},
    "GR": {"name":"Greece","callingcode":"30", "currency":"EUR", "lang":"el"},
    "GS": {"name":"South Georgia and the South Sandwich Islands","callingcode":"500", "currency":"USD", "lang":"ka"},
    "GT": {"name":"Guatemala","callingcode":"502", "currency":"GTQ", "lang":"es"},
    "GU": {"name":"Guam","callingcode":"1-671", "currency":"USD", "lang":"en"},
    "GW": {"name":"Guinea-Bissau","callingcode":"245", "currency":"XOF", "lang":"pt"},
    "GY": {"name":"Guyana","callingcode":"592", "currency":"GYD", "lang":"en"},
    "HK": {"name":"Hong Kong","callingcode":"852", "currency":"HKD", "lang":"zh-CN"},
    "HN": {"name":"Honduras","callingcode":"504", "currency":"HNL", "lang":"es"},
    "HR": {"name":"Croatia","callingcode":"385", "currency":"EUR", "lang":"hr"},
    "HT": {"name":"Haiti","callingcode":"509", "currency":"HTG", "lang":"fr"},
    "HU": {"name":"Hungary","callingcode":"36", "currency":"HUF", "lang":"hu"},
    "ID": {"name":"Indonesia","callingcode":"62", "currency":"IDR", "lang":"id"},
    "IE": {"name":"Ireland","callingcode":"353", "currency":"EUR", "lang":"en"},
    "IL": {"name":"Israel","callingcode":"972", "currency":"ILS", "lang":"he"},
    "IM": {"name":"Isle of Man","callingcode":"44-1624", "currency":"USD", "lang":"en"},
    "IN": {"name":"India","callingcode":"91", "currency":"INR", "lang":"en"},
    "IO": {"name":"British Indian Ocean Territory","callingcode":"246", "currency":"USD", "lang":"en"},
    "IQ": {"name":"Iraq","callingcode":"964", "currency":"NID", "lang":"ar"},
    "IR": {"name":"Iran, Islamic Republic of","callingcode":"98", "currency":"USD", "lang":"fa"},
    "IS": {"name":"Iceland","callingcode":"354", "currency":"ISK", "lang":"en"},
    "IT": {"name":"Italy","callingcode":"39", "currency":"EUR", "lang":"it"},
    "JE": {"name":"Jersey","callingcode":"44-1534", "currency":"GBP", "lang":"en"},
    "JM": {"name":"Jamaica","callingcode":"1-876", "currency":"JMD", "lang":"en"},
    "JO": {"name":"Jordan","callingcode":"962", "currency":"JOD", "lang":"ar"},
    "JP": {"name":"Japan","callingcode":"81", "currency":"JPY", "lang":"ja"},
    "KE": {"name":"Kenya","callingcode":"254", "currency":"KES", "lang":"en"},
    "KG": {"name":"Kyrgyzstan","callingcode":"996", "currency":"USD", "lang":"ru"},
    "KH": {"name":"Cambodia","callingcode":"855", "currency":"KHR", "lang":"km"},
    "KI": {"name":"Kiribati","callingcode":"686", "currency":"AUD", "lang":"en"},
    "KM": {"name":"Comoros","callingcode":"269", "currency":"USD", "lang":"ar"},
    "KN": {"name":"Saint Kitts and Nevis","callingcode":"1-869", "currency":"XCD", "lang":"en"},
    "KP": {"name":"Korea, Democratic People\'s Republic of","callingcode":"850", "currency":"USD", "lang":"ko"},
    "KP": {"name":"Korea","callingcode":"850", "currency":"USD", "lang":"ko"},
    "KR": {"name":"Korea, Republic of","callingcode":"82", "currency":"KRW", "lang":"ko"},
    "KW": {"name":"Kuwait","callingcode":"965", "currency":"KWD", "lang":"ar"},
    "KY": {"name":"Cayman Islands","callingcode":"1-345", "currency":"KYD", "lang":"en"},
    "KZ": {"name":"Kazakhstan","callingcode":"7", "currency":"KZT", "lang":"ru"},
    "LA": {"name":"Lao People\'s Democratic Republic","callingcode":"856", "currency":"LAK", "lang":"lo"},
    "LB": {"name":"Lebanon","callingcode":"961", "currency":"LBP", "lang":"ar"},
    "LC": {"name":"Saint Lucia","callingcode":"1-758", "currency":"XCD", "lang":"en"},
    "LI": {"name":"Liechtenstein","callingcode":"423", "currency":"CHF", "lang":"de"},
    "LK": {"name":"Sri Lanka","callingcode":"94", "currency":"LKR", "lang":"si"},
    "LR": {"name":"Liberia","callingcode":"231", "currency":"LRD", "lang":"en"},
    "LS": {"name":"Lesotho","callingcode":"266", "currency":"LSL", "lang":"en"},
    "LT": {"name":"Lithuania","callingcode":"370", "currency":"LTL", "lang":"lt"},
    "LU": {"name":"Luxembourg","callingcode":"352", "currency":"EUR", "lang":"fr"},
    "LV": {"name":"Latvia","callingcode":"371", "currency":"LVL", "lang":"ru"},
    "LY": {"name":"Libya","callingcode":"218", "currency":"LYD", "lang":"ar"},
    "MA": {"name":"Morocco","callingcode":"212", "currency":"MAD", "lang":"ar"},
    "MC": {"name":"Monaco","callingcode":"377", "currency":"EUR", "lang":"fr"},
    "MD": {"name":"Moldova, Republic of","callingcode":"373", "currency":"MDL", "lang":"ru"},
    "ME": {"name":"Montenegro","callingcode":"382", "currency":"EUR", "lang":"sr"},
    "MG": {"name":"Madagascar","callingcode":"261", "currency":"MGA", "lang":"fr"},
    "MH": {"name":"Marshall Islands","callingcode":"692", "currency":"USD", "lang":"en"},
    "MK": {"name":"Macedonia, the former Yugoslav Republic of","callingcode":"389", "currency":"EUR", "lang":"mk"},
    "ML": {"name":"Mali","callingcode":"223", "currency":"XOF", "lang":"fr"},
    "MM": {"name":"Myanmar","callingcode":"95", "currency":"USD", "lang":"my"},
    "MN": {"name":"Mongolia","callingcode":"976", "currency":"MNT", "lang":"mn"},
    "MO": {"name":"Macao","callingcode":"853", "currency":"MOP", "lang":"en"},
    "MP": {"name":"Northern Mariana Islands","callingcode":"1-670", "currency":"USD", "lang":"en"},
    "MZ": {"name":"Martinique","callingcode":"258", "currency":"MZM", "lang":"en"},
    "MR": {"name":"Mauritania","callingcode":"222", "currency":"MRO", "lang":"ar"},
    "MS": {"name":"Montserrat","callingcode":"1-664", "currency":"XCD", "lang":"en"},
    "MT": {"name":"Malta","callingcode":"356", "currency":"EUR", "lang":"en"},
    "MU": {"name":"Mauritius","callingcode":"230", "currency":"MUR", "lang":"en"},
    "MV": {"name":"Maldives","callingcode":"960", "currency":"MVR", "lang":"en"},
    "MW": {"name":"Malawi","callingcode":"265", "currency":"MWK", "lang":"ny"},
    "MX": {"name":"Mexico","callingcode":"52", "currency":"MXN", "lang":"es"},
    "MY": {"name":"Malaysia","callingcode":"60", "currency":"MYR", "lang":"my"},
    "MZ": {"name":"Mozambique","callingcode":"258", "currency":"MZM", "lang":"pt"},
    "NA": {"name":"Namibia","callingcode":"264", "currency":"NAD", "lang":"es"},
    "NC": {"name":"New Caledonia","callingcode":"687", "currency":"XPF", "lang":"en"},
    "NE": {"name":"Niger","callingcode":"227", "currency":"XOF", "lang":"fr"},
    "NF": {"name":"Norfolk Island","callingcode":"672", "currency":"AUD", "lang":"en"},
    "NG": {"name":"Nigeria","callingcode":"234", "currency":"NGN", "lang":"en"},
    "NI": {"name":"Nicaragua","callingcode":"505", "currency":"NIO", "lang":"es"},
    "NL": {"name":"Netherlands","callingcode":"31", "currency":"EUR", "lang":"nl"},
    "NO": {"name":"Norway","callingcode":"47", "currency":"NOK", "lang":"no"},
    "NP": {"name":"Nepal","callingcode":"977", "currency":"NPR", "lang":"ne"},
    "NR": {"name":"Nauru","callingcode":"674", "currency":"USD", "lang":"na"},
    "NU": {"name":"Niue","callingcode":"683", "currency":"USD", "lang":"en"},
    "NZ": {"name":"New Zealand","callingcode":"64", "currency":"NZD", "lang":"en"},
    "OM": {"name":"Oman","callingcode":"968", "currency":"OMR", "lang":"ar"},
    "PA": {"name":"Panama","callingcode":"507", "currency":"PAB", "lang":"es"},
    "PE": {"name":"Peru","callingcode":"51", "currency":"PEN", "lang":"es"},
    "PF": {"name":"French Polynesia","callingcode":"689", "currency":"XPF", "lang":"en"},
    "PS": {"name":"Palestine","callingcode":"970", "currency":"EUR", "lang":"en"},
    "PG": {"name":"Papua New Guinea","callingcode":"675", "currency":"PGK", "lang":"en"},
    "PH": {"name":"Philippines","callingcode":"63", "currency":"PHP", "lang":"en"},
    "PK": {"name":"Pakistan","callingcode":"92", "currency":"PKR", "lang":"en"},
    "PL": {"name":"Poland","callingcode":"48", "currency":"PLN", "lang":"pl","currency_symbol":"zł"},
    "PN": {"name":"Pitcairn","callingcode":"64", "currency":"USD", "lang":"en"},
    "PR": {"name":"Puerto Rico","callingcode":"1-787", "currency":"USD", "lang":"en"},
    "PT": {"name":"Portugal","callingcode":"351", "currency":"EUR", "lang":"pt","currency_symbol":"S/."},
    "PW": {"name":"Palau","callingcode":"680", "currency":"USD", "lang":"en"},
    "PY": {"name":"Paraguay","callingcode":"595", "currency":"PYG", "lang":"es"},
    "QA": {"name":"Qatar","callingcode":"974", "currency":"QAR", "lang":"ar"},
    "RE": {"name":"Réunion","callingcode":"262", "currency":"EUR", "lang":"en"},
    "RO": {"name":"Romania","callingcode":"40", "currency":"ROL", "lang":"ro"},
    "RS": {"name":"Serbia","callingcode":"381", "currency":"EUR", "lang":"sr"},
    "RU": {"name":"Russian Federation","callingcode":"7", "currency":"RUB", "lang":"en"},
    "RW": {"name":"Rwanda","callingcode":"250", "currency":"RWF", "lang":"en"},
    "SA": {"name":"Saudi Arabia","callingcode":"966", "currency":"SAR", "lang":"ar"},
    "SB": {"name":"Solomon Islands","callingcode":"677", "currency":"SBD", "lang":"en"},
    "SC": {"name":"Seychelles","callingcode":"248", "currency":"SCR", "lang":"en"},
    "SD": {"name":"Sudan","callingcode":"249", "currency":"USD", "lang":"ar"},
    "SE": {"name":"Sweden","callingcode":"46", "currency":"SEK", "lang":"sv"},
    "SG": {"name":"Singapore","callingcode":"65", "currency":"SGD", "lang":"en"},
    "SH": {"name":"Saint Helena, Ascension and Tristan da Cunha","callingcode":"290", "currency":"EUR", "lang":"en"},
    "SI": {"name":"Slovenia","callingcode":"386", "currency":"EUR", "lang":"en"},
    "SK": {"name":"Slovakia","callingcode":"421", "currency":"EUR", "lang":"sk"},
    "SL": {"name":"Sierra Leone","callingcode":"232", "currency":"SLL", "lang":"en"},
    "SM": {"name":"San Marino","callingcode":"378", "currency":"EUR", "lang":"it"},
    "SN": {"name":"Senegal","callingcode":"221", "currency":"XOF", "lang":"fr"},
    "SO": {"name":"Somalia","callingcode":"252", "currency":"USD", "lang":"so"},
    "SR": {"name":"Suriname","callingcode":"597", "currency":"SRG", "lang":"nl"},
    "SS": {"name":"South Sudan","callingcode":"211", "currency":"ANG", "lang":"en"},
    "ST": {"name":"Sao Tome and Principe","callingcode":"239", "currency":"USD", "lang":"pt"},
    "SV": {"name":"El Salvador","callingcode":"503", "currency":"USD", "lang":"es"},
    "SX": {"name":"Sint Maarten (Dutch part)","callingcode":"1-721", "currency":"USD", "lang":"en"},
    "SY": {"name":"Syrian Arab Republic","callingcode":"963", "currency":"USD", "lang":"ar"},
    "SZ": {"name":"Swaziland","callingcode":"268", "currency":"SZL", "lang":"en"},
    "TC": {"name":"Turks and Caicos Islands","callingcode":"1-649", "currency":"USD", "lang":"en","currency_symbol":"$"},
    "TD": {"name":"Chad","callingcode":"235", "currency":"XAF", "lang":"fr"},
    "TF": {"name":"French Southern Territories","callingcode":"262", "currency":"USD", "lang":"en","currency_symbol":"$"},
    "TG": {"name":"Togo","callingcode":"228", "currency":"XOF", "lang":"fr"},
    "TH": {"name":"Thailand","callingcode":"66", "currency":"THB", "lang":"th"},
    "TJ": {"name":"Tajikistan","callingcode":"992", "currency":"TJS", "lang":"tg"},
    "TK": {"name":"Tokelau","callingcode":"690", "currency":"USD", "lang":"en"},
    "TL": {"name":"Timor-Leste","callingcode":"670", "currency":"USD", "lang":"en","currency_symbol":"$"},
    "TM": {"name":"Turkmenistan","callingcode":"993", "currency":"TMM", "lang":"tk"},
    "TN": {"name":"Tunisia","callingcode":"216", "currency":"TND", "lang":"ar"},
    "TO": {"name":"Tonga","callingcode":"676", "currency":"TOP", "lang":"en","currency_symbol":"$"},
    "TR": {"name":"Turkey","callingcode":"90", "currency":"USD", "lang":"tr"},
    "TT": {"name":"Trinidad and Tobago","callingcode":"1-868", "currency":"TTD", "lang":"en"},
    "TV": {"name":"Tuvalu","callingcode":"688", "currency":"AUD", "lang":"en","currency_symbol":"$"},
    "TZ": {"name":"Tanzania, United Republic of","callingcode":"255", "currency":"TZS", "lang":"en"},
    "TW": {"name":"Taiwan, Province of China","callingcode":"886", "currency":"TWD", "lang":"zh-TW"},
    "UA": {"name":"Ukraine","callingcode":"380", "currency":"UAH", "lang":"uk"},
    "UG": {"name":"Uganda","callingcode":"256", "currency":"UGX", "lang":"en","currency_symbol":"$"},
    "US": {"name":"United States","callingcode":"1", "currency":"USD", "lang":"en","currency_symbol":"$"},
    "UY": {"name":"Uruguay","callingcode":"598", "currency":"UYU", "lang":"es"},
    "UZ": {"name":"Uzbekistan","callingcode":"998", "currency":"UZS", "lang":"uz"},
    "VA": {"name":"Holy See (Vatican City State)","callingcode":"379", "currency":"EUR", "lang":"it"},
    "VC": {"name":"Saint Vincent and the Grenadines","callingcode":"1-784", "currency":"XCD", "lang":"en"},
    "VE": {"name":"Venezuela, Bolivarian Republic of","callingcode":"58", "currency":"VEB", "lang":"es"},
    "VG": {"name":"Virgin Islands, British","callingcode":"1-284", "currency":"USD", "lang":"en"},
    "VI": {"name":"Virgin Islands, U.S.","callingcode":"1-340", "currency":"USD", "lang":"en"},
    "VN": {"name":"Viet Nam","callingcode":"84", "currency":"VND", "lang":"vi"},
    "VU": {"name":"Vanuatu","callingcode":"678", "currency":"VUV", "lang":"en"},
    "WS": {"name":"Samoa","callingcode":"685", "currency":"WST", "lang":"en"},
    "YE": {"name":"Yemen","callingcode":"967", "currency":"YER", "lang":"ar"},
    "ZA": {"name":"South Africa","callingcode":"27", "currency":"ZAR", "lang":"en"},
    "ZM": {"name":"Zambia","callingcode":"260", "currency":"ZMK", "lang":"en"},
    "ZW": {"name":"Zimbabwe","callingcode":"263", "currency":"ZWD", "lang":"en"}
}';